### ISSUE TITLE
Cant roll for Villains and Monsters

### ISSUE THREAD

**Issue by CaioLourencio** [Detailing-the-Realm/svnsea2e#108]
Hi Everyone, first of all thank you for the amazing work!

I cannot roll villains and monsters traits in the Foundry version 9. But there is no error message.

**Comment by Thomas-Maurer** [comment]
This was fixed in the develop branch. It was this Pull request : https://github.com/Detailing-the-Realm/svnsea2e/pull/107

**Comment by CaioLourencio** [comment]
Thanks!
