### ISSUE TITLE
probleme with roll dice for vilain

### ISSUE THREAD

**Issue by ZolOnTheNet** [Detailing-the-Realm/svnsea2e#114]
I have a problem when a want to roll vilain's influence or strength : a js error due to a lack of value userForMe and UserForHelpMe input box. I don't know if you are same error (foundryvtt v10.284)
error 1 : 
Uncaught (in promise) TypeError: form.useForMe is undefined
    _spendHeroPoint roll.js:83

error 2  : Uncaught (in promise) TypeError: form.useForHelpMe is undefined
    _calculBonusDice roll.js:71

a solve the problem with add in trail-roll-dialog.html

>  
<input  type="hidden" id="useForMe" name="useForMe" value="0" / >
 <input type="hidden" id="useForHelpMe" name="useForMe" value="0" / >

I knows is not elegant but it's work for now... Normaly you need to more protect then test of useForMe (line 83) and useForHelpMe (lien 71) but i learn javascript and i don't know to do that a this time...

thank for you job ! 
ps: i'm not fluent english..., sorry for that so...

**Comment by Thomas-Maurer** [comment]
This was fixed in : https://github.com/Detailing-the-Realm/svnsea2e/pull/107

**Comment by Armaklan** [comment]
Resolve in #107
