### ISSUE TITLE
Make wounds editable so they can be reset to 0

### ISSUE THREAD

**Issue by Faro1991** [Detailing-the-Realm/svnsea2e#23]
As the title says. Was playing around with the new looks and for fun assigned a wound to a player character's sheet that cannot be removed anymore.  Might be a bug, but writing it as a user story just in case.

Player/GM wants to be able to reset a character's regular wounds to 0.

**Acceptance Criterium**
Wounds can be reset to 0 by clicking to the left of the first wound, as is already possible for dramatic wounds.

**Alternative Acceptance Criterium**
Character sheet gets a "reset wounds" button that opens up a dialogue to rest wounds to 0, differentiating between regular and dramatic wounds.

**Comment by psychoph** [comment]
Can you document the steps you took to cause this? 

The way I have it setup right now you click on heart one then you have to click on hear one again to make all heart blank. I can't think of another way to set it to zero other than having a reset button or something.

**Comment by Faro1991** [comment]
I'm trying exactly that and it simply doesn't work. All that'll do is keep the hero at one wound. For the dramatic wounds it works just fine.

**Comment by psychoph** [comment]
Ok. I will try the same tonight and see if I can figure out what the problem is. This is on the hero sheet or the player character sheet? I haven’t checked the hero sheet.

**Comment by Faro1991** [comment]
> Ok. I will try the same tonight and see if I can figure out what the problem is. This is on the hero sheet or the player character sheet? I haven’t checked the hero sheet.

On both actually. Accidentally created my PCs with the Hero sheets first (and was wondering why there was no option for hero points, lol)

**Comment by psychoph** [comment]
https://foundry.jasonhardin.com/imgs/uploads/2020-11-05_20-41-14.mp4

I recorded a video of me adding and removing wounds. I can't replicate the issue. I did notice I have an issue with corruption though.
