### ISSUE TITLE
Macro edit screen missing parts

### ISSUE THREAD

**Issue by ClayRobeson** [Detailing-the-Realm/svnsea2e#30]
When creating or editing macros, it seems that the macro title and icon section of the macro screen is missing.  It's missing even if all modules are deactivated, and it's present in a generic sandbox system.  So, I'm guessing it's a bug, because I don't know what else to try.
![macro](https://user-images.githubusercontent.com/70825424/102001581-86487580-3ca8-11eb-95f5-074491ca5b4c.png)

**Comment by psychoph** [comment]
I figured out why this is. I have some css that causes overflow to be hidden in sheet headers and that is causing those fields to not display. I will fix this in the next release.
