### ISSUE TITLE
Incompatible with Foundry 8.x

### ISSUE THREAD

**Issue by Gondlar** [Detailing-the-Realm/svnsea2e#41]
Foundry 8.x saw a couple of changes under the hood, especially regarding DocumentSheet#entity. As a result, this module currently does not work under Foundry 8.x

Trying to open a chatacter sheet fails and produces the errors seen in this iamge:
![2021-06-09-173231_541x544_scrot](https://user-images.githubusercontent.com/6443311/121385579-87055000-c949-11eb-9fa4-67ec4515b354.png)

**Comment by bakadevil** [comment]
Same problem here. Any update ?

**Comment by Gondlar** [comment]
I am working on a fix in my fork of this repository and I intend to open a PR at some point. However, it's not quite ready yet. However, feel free to help test it, most features should be back up and running.

**Comment by bakadevil** [comment]
Oh ! Great news ! If you don't mind, I'll test it... but I'm not very smart so, I don't know If I can help. Thanks for you answers !

**Comment by Gondlar** [comment]
I was about to link my fix here now that it's finally ready, but I see Matt has already fixed it in the meantime and his fix looks more comprehensive than mine, so I suggest using his work.

**Comment by mattraykowski** [comment]
It looks like I still have to fix the Fate tab - the Virtue and Hubris code seems inconsistent. I also haven't fully tested whether my changes are backwards compatible.

Unfortunately this project is unlicensed and with no responses from the author I'm not really sure what else I can do with my work.

**Comment by ClayRobeson** [comment]
@mattraykowski

Looks like psychoph wasn't getting updates from Github that anything was going on here.  I pinged him in Discord, and he's going to take a look when he's back at his desktop machine.

**Comment by psychoph** [comment]
@mattraykowski and @Gondlar would either or both of you like to take over the maintenance of this system? I can give you access to push the pull requests, I am not seeing them in the pull requests for here (looks like you forked and did everything in your own repo). I am happy to add you both here or move the project to one of your repositories. My 7th sea game died and I have other life stuff taking my time.

**Comment by Gondlar** [comment]
I'm not a huge Javascript guy. Going by the code I've seen, I think @mattraykowski would be the more qualified among the two of us to do that, so if he wants to, I'll happily pass. I have been fixing stuff mainly because a friend of mine is using the system and have taken it as an opportunity to learn. If Matt doesn't want to take over, I'll talk to that friend. If he will still be using the system in the foreseeable future, I can take over the project.

**Comment by mattraykowski** [comment]
I messaged @psychoph privately, I'm more than happy to take over maintenance of this project. I just wanted to make sure I understood where we're at. I'm not likely to wrap up this issue and merge it soon with the US holiday coming up - but who knows. I'll try and keep the issue apprised of my progress.

**Comment by ClayRobeson** [comment]
Thanks, @mattraykowski! I'd offer to help if I actually knew ANYTHING.  But I will offer moral support?

**Comment by mattraykowski** [comment]
Initial testing looks good, thanks @Armaklan for the help!
