### ISSUE TITLE
Problem z villain card 

### ISSUE THREAD

**Issue by wolfang55** [Detailing-the-Realm/svnsea2e#70]
Hi 
I thank you for your work and amazing module to 7th sea.
Unfortunately, I notice today, that I can't add advantages to the villain sheet. I click on add button, but it doesn't work. I don't know, what is the reason for this problem. 
Best regards 
Mateusz

**Comment by mattraykowski** [comment]
I have confirmed this. I will try and get a fix in to the 3.0 release.

**Comment by wolfang55** [comment]
Thank you for your fast help. Now I can prepare a cruel nemesis for my players
Best regards 
Mateusz
