### ISSUE TITLE
Cannot add Advantages or other items to character sheets.

### ISSUE THREAD

**Issue by greylurk** [Detailing-the-Realm/svnsea2e#86]
Using Foundry v9 with svnsea2e, I'm unable to add advantages or other items to the character sheets.

There is a javascript error reported:

![image](https://user-images.githubusercontent.com/515023/151722119-eb29544d-dc1e-46c3-a769-65aa34fc49ac.png)

**Comment by Armaklan** [comment]
This version is not compatible with Foundry VTT 9. We work on this : 
https://github.com/Detailing-the-Realm/svnsea2e/issues/78

I close this ticket to keep only the main compatibility issue.
