### ISSUE TITLE
Additional Sorcery Info

### ISSUE THREAD

**Issue by ClayRobeson** [Detailing-the-Realm/svnsea2e#9]
Again, thank you for this.  Today's update blew me away. 👍 

I've been working sorcery information in from other source books, and figured you might want some of it.

/lang/en.json
	
  add

  "SVNSEA2E.SorceryAlquimia": "Alquimia",
  "SVNSEA2E.Juvenilia": "Juvenilia",  
  "SVNSEA2E.MagnumOpus": "Magnum Opus",
  "SVNSEA2E.SorceryGaldr": "Galdr",
  "SVNSEA2E.Rune": "Rune",
  "SVNSEA2E.Patron": "Patron",

/module/config.js 

add

in SVNSEA2E.sorceryTypes = {  

  alchemy: 'SVNSEA2E.SorceryAlquimia',
  galdr: 'SVNSEA2E.SorceryGaldr',
  
in SVNSEA2E.sorceryCats = {   

  juvenilia: 'SVNSEA2E.Juvenilia',
  magnum: 'SVNSEA2E.MagnumOpus',
  rune: 'SVNSEA2E.Rune',
  patron: 'SVNSEA2E.Patron',

**Comment by psychoph** [comment]
Nevermind I found these in the nations of theah books. I missed them originally.
