### ISSUE TITLE
Issue with backgrounds

### ISSUE THREAD

**Issue by EntreriCansinos** [Detailing-the-Realm/svnsea2e#92]
In advance, great job with the update to V9.
Dragging backgrounds on the character sheet do not appear and do not transfer associated advantages.
Thank you for your dedication and efforts.

**Comment by Thomas-Maurer** [comment]
Hi, this [PR](https://github.com/Detailing-the-Realm/svnsea2e/pull/95) should fix your issue.

**Comment by greylurk** [comment]
Adding backgrounds works, as long as there are no abilities on those backgrounds.  It *does* look like @Thomas-Maurer 's PR addresses the issue.
