### ISSUE TITLE
The feature to count how many dice are left over when counting raises (Traitor Dice)

### ISSUE THREAD

**Issue by JSpring3** [Detailing-the-Realm/svnsea2e#97]
The feature to count how many dice are left over when counting raises (Traitor Dice)
Example Set [2,2,3,3,5,6,8,10]
Raise 1 = 10
Raise 2 = 2,5,6
Raise 3 = 2,3,5

Traitor Dice 8

**Comment by Armaklan** [comment]
Merge on develop.
